# Generated by Django 4.2.6 on 2024-03-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0028_remove_shifttiming_cleaning_downtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='machine_id',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
