# Generated by Django 4.2.6 on 2024-03-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0029_machine_machine_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifttiming',
            name='cleaning_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shifttiming',
            name='cleaning_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shifttiming',
            name='lunch_break_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shifttiming',
            name='lunch_break_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shifttiming',
            name='spell_downtime',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shifttiming',
            name='tea_break_1_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shifttiming',
            name='tea_break_1_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shifttiming',
            name='tea_break_2_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shifttiming',
            name='tea_break_2_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shifttiming',
            name='tea_break_3_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shifttiming',
            name='tea_break_3_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
