# Generated by Django 4.2.5 on 2023-09-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreakdownCategory',
            fields=[
                ('breakdownCategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('breakdownCategoryName', models.CharField(max_length=100)),
            ],
        ),
    ]
