# Generated by Django 4.2.5 on 2023-09-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('shiftId', models.AutoField(primary_key=True, serialize=False)),
                ('shift_name', models.CharField(max_length=100)),
                ('shift_start_time', models.TimeField()),
                ('shift_end_time', models.TimeField()),
                ('lunch_start_time', models.TimeField()),
                ('lunch_end_time', models.TimeField()),
            ],
        ),
    ]
