# Generated by Django 4.2.5 on 2023-09-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skf', '0004_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assemblyline',
            fields=[
                ('assemblylineId', models.AutoField(primary_key=True, serialize=False)),
                ('assemblylineName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationId', models.AutoField(primary_key=True, serialize=False)),
                ('locationName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shopfloor',
            fields=[
                ('shopfloorId', models.AutoField(primary_key=True, serialize=False)),
                ('shopfloorName', models.CharField(max_length=100)),
            ],
        ),
    ]
