# Generated by Django 4.2.5 on 2023-09-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skf', '0005_assemblyline_location_shopfloor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machineId', models.AutoField(primary_key=True, serialize=False)),
                ('machineName', models.CharField(max_length=100)),
            ],
        ),
    ]
