# Generated by Django 4.2.5 on 2023-09-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skf', '0007_andon'),
    ]

    operations = [
        migrations.AddField(
            model_name='andon',
            name='alert_shift',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='andon',
            name='assemblyline',
            field=models.CharField(default='CHANNEL 5', max_length=30),
        ),
        migrations.AddField(
            model_name='andon',
            name='company',
            field=models.CharField(default='SKF', max_length=10),
        ),
        migrations.AddField(
            model_name='andon',
            name='location',
            field=models.CharField(default='BLR', max_length=10),
        ),
        migrations.AddField(
            model_name='andon',
            name='shopfloor',
            field=models.CharField(default='BALL BEARING', max_length=30),
        ),
        migrations.AlterField(
            model_name='andon',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='andon',
            name='login',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='andon',
            name='machineId',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='andon',
            name='sub_category',
            field=models.CharField(max_length=50),
        ),
    ]
