# Generated by Django 4.2.5 on 2023-09-11 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skf', '0008_andon_alert_shift_andon_assemblyline_andon_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='andon',
            name='login',
        ),
    ]
