# Generated by Django 4.2.5 on 2023-09-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skf', '0009_remove_andon_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andon',
            name='sub_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
