# Generated by Django 4.2.5 on 2023-09-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skf', '0010_alter_andon_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andon',
            name='andon_acknowledge',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='andon',
            name='andon_resolved',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
