# Generated by Django 4.2.5 on 2023-09-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skf', '0012_alter_andon_andon_acknowledge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AndonData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(default='SKF', max_length=10)),
                ('location', models.CharField(default='BLR', max_length=10)),
                ('shopfloor', models.CharField(default='BALL BEARING', max_length=30)),
                ('assemblyline', models.CharField(max_length=30)),
                ('machineId', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('sub_category', models.CharField(blank=True, max_length=50, null=True)),
                ('alert_shift', models.CharField(max_length=10)),
                ('andon_alerts', models.DateTimeField(blank=True, null=True)),
                ('andon_acknowledge', models.DateTimeField(blank=True, null=True)),
                ('andon_resolved', models.DateTimeField(blank=True, null=True)),
                ('total_time', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'andon_data',
            },
        ),
        migrations.CreateModel(
            name='BreakdownHMI',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('machine_id', models.CharField(max_length=55)),
                ('channel_id', models.CharField(max_length=55)),
                ('timestamp', models.DateTimeField()),
                ('breakdown_alert', models.CharField(max_length=255)),
                ('alert_value', models.IntegerField()),
            ],
            options={
                'db_table': 'breakdown_hmi',
            },
        ),
        migrations.AlterField(
            model_name='andon',
            name='andon_acknowledge',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='andon',
            name='andon_alerts',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='andon',
            name='andon_resolved',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
