# Generated by Django 4.2.5 on 2023-09-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skf', '0013_andondata_breakdownhmi_alter_andon_andon_acknowledge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdownhmi',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
