# Generated by Django 4.2.5 on 2023-09-21 16:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('skf', '0014_alter_breakdownhmi_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdownhmi',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
