# Generated by Django 4.2.5 on 2023-09-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skf', '0015_alter_breakdownhmi_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='andon',
            name='alert_shift',
        ),
        migrations.RemoveField(
            model_name='andon',
            name='company',
        ),
        migrations.RemoveField(
            model_name='andon',
            name='location',
        ),
        migrations.RemoveField(
            model_name='andon',
            name='shopfloor',
        ),
        migrations.AlterField(
            model_name='breakdownhmi',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
