# Generated by Django 4.2.5 on 2023-09-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skf', '0018_andondata_alert_shift_andondata_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andondata',
            name='andon_acknowledge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='andondata',
            name='andon_alerts',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='andondata',
            name='andon_resolved',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
