# Generated by Django 4.2.5 on 2023-09-23 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skf', '0019_alter_andondata_andon_acknowledge_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='andondata',
            unique_together={('machineId', 'category', 'assemblyline')},
        ),
    ]
