# Generated by Django 4.2.5 on 2023-09-24 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skf', '0021_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
