# Generated by Django 4.2.5 on 2023-09-26 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skf', '0023_andondata_repair_time_andondata_respose_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='andondata',
            old_name='respose_time',
            new_name='response_time',
        ),
    ]
