# Generated by Django 4.2.5 on 2023-09-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skf', '0024_rename_respose_time_andondata_response_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andondata',
            name='shopfloor',
            field=models.CharField(default='GRINDING', max_length=30),
        ),
    ]
