# Generated by Django 4.2.5 on 2023-10-05 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skf', '0025_alter_andondata_shopfloor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='andondata',
            unique_together=set(),
        ),
    ]
