# Generated by Django 4.2.5 on 2023-10-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skf', '0026_alter_andondata_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andondata',
            name='location',
            field=models.CharField(default='PUNE', max_length=10),
        ),
        migrations.AlterField(
            model_name='andondata',
            name='shopfloor',
            field=models.CharField(default='TRB BEARING', max_length=30),
        ),
    ]
