# Generated by Django 4.2.5 on 2023-09-24 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_user_name_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
