# Generated by Django 4.2.6 on 2025-04-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown', '0002_delete_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='andondata',
            name='raise_alert',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='andondata',
            name='resolution',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='andondata',
            name='andon_acknowledge',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='andondata',
            name='andon_alerts',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='andondata',
            name='andon_resolved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='andondata',
            name='repair_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='andondata',
            name='response_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='andondata',
            name='total_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
