# Generated by Django 4.2.6 on 2025-05-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown', '0003_andondata_raise_alert_andondata_resolution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andondata',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
