# Generated by Django 4.2.6 on 2025-05-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown', '0004_alter_andondata_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andondata',
            name='alert_shift',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='andondata',
            name='assemblyline',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='andondata',
            name='company',
            field=models.CharField(default='SKF', max_length=100),
        ),
        migrations.AlterField(
            model_name='andondata',
            name='location',
            field=models.CharField(default='BLR', max_length=100),
        ),
        migrations.AlterField(
            model_name='andondata',
            name='shopfloor',
            field=models.CharField(default='GRINDING', max_length=300),
        ),
    ]
