# Generated by Django 4.2.6 on 2024-12-04 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assemblyLineWiseData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plant', models.CharField(max_length=255)),
                ('shopfloor', models.CharField(max_length=255)),
                ('assemblyline', models.CharField(max_length=255)),
                ('machine_id', models.CharField(max_length=255)),
                ('product_id', models.CharField(max_length=255)),
                ('date_production', models.CharField(max_length=255)),
                ('shift_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='productionPlanning',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_id', models.CharField(default='', max_length=100, unique=True)),
                ('employee_id', models.CharField(default='1', max_length=100)),
                ('product_id', models.CharField(max_length=100)),
                ('drawing_no', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.CharField(max_length=100)),
                ('po_no', models.CharField(max_length=100)),
                ('batch_no', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('assigned_date', models.DateField(blank=True, null=True)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('planned_date', models.CharField(blank=True, null=True)),
                ('processing_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('required_time', models.CharField(blank=True, max_length=255, null=True)),
                ('product_target', models.DurationField(blank=True, null=True)),
            ],
            options={
                'db_table': 'production_planning',
            },
        ),
        migrations.CreateModel(
            name='soloAssemblyLineData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stage_no', models.IntegerField()),
                ('stage', models.CharField(max_length=255)),
                ('mc_on_hours', models.FloatField(blank=True, null=True)),
                ('mc_idle_hours', models.FloatField(blank=True, null=True)),
                ('actual', models.IntegerField(blank=True, null=True)),
                ('target', models.IntegerField(blank=True, null=True)),
                ('performance', models.FloatField(blank=True, null=True)),
                ('gap', models.IntegerField(blank=True, null=True)),
                ('current', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('shift', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'solo_assembly_line_data',
            },
        ),
        migrations.CreateModel(
            name='spellAssemblyLineData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stage_no', models.IntegerField()),
                ('stage', models.CharField(max_length=255)),
                ('mc_on_hours', models.IntegerField(blank=True, null=True)),
                ('mc_idle_hours', models.IntegerField(blank=True, null=True)),
                ('actual', models.IntegerField(blank=True, null=True)),
                ('target', models.IntegerField(blank=True, null=True)),
                ('performance', models.FloatField(blank=True, null=True)),
                ('gap', models.IntegerField(blank=True, null=True)),
                ('current', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('shift', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'spell_assembly_line_data',
            },
        ),
        migrations.CreateModel(
            name='ProductionAndon',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('machine_id', models.CharField(blank=True, max_length=255, null=True)),
                ('machine_datetime', models.DateTimeField(blank=True, null=True)),
                ('r', models.CharField(blank=True, max_length=255, null=True)),
                ('p', models.IntegerField(blank=True, null=True)),
                ('kwh_reading', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'production_andon',
                'unique_together': {('machine_datetime', 'machine_id')},
            },
        ),
        migrations.CreateModel(
            name='machineWiseData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plant', models.CharField(default='Bangalore', max_length=255)),
                ('shopfloor', models.CharField(default='Production', max_length=255)),
                ('assembly_line', models.CharField(default='Line - 1', max_length=255)),
                ('machine_id', models.CharField(max_length=255)),
                ('product_target', models.IntegerField(default=600)),
                ('time', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('on_time', models.FloatField(blank=True, null=True)),
                ('idle_time', models.FloatField(blank=True, null=True)),
                ('actual', models.IntegerField(blank=True, null=True)),
                ('target', models.IntegerField(blank=True, default=10, null=True)),
                ('performance', models.FloatField(blank=True, null=True)),
                ('current', models.FloatField(blank=True, null=True)),
                ('gap', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'machine_wise_data',
                'unique_together': {('machine_id', 'date', 'time')},
            },
        ),
        migrations.CreateModel(
            name='lineMachineSlotConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=255)),
                ('plant', models.CharField(max_length=255)),
                ('shopfloor', models.CharField(max_length=255)),
                ('assembly_line', models.CharField(max_length=255)),
                ('machine_id', models.CharField(max_length=255)),
                ('product_id', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('shift_a', models.CharField(blank=True, max_length=255, null=True)),
                ('shift_b', models.CharField(blank=True, max_length=255, null=True)),
                ('shift_c', models.CharField(blank=True, max_length=255, null=True)),
                ('planned_hours', models.IntegerField()),
                ('planned_production', models.IntegerField(blank=True, null=True)),
                ('remaining_hours', models.IntegerField()),
                ('balance_production', models.IntegerField()),
                ('manager', models.CharField(default='XYZ', max_length=255)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_machine_slot_config', to='production.productionplanning')),
            ],
            options={
                'db_table': 'line_machine_slot_config',
            },
        ),
        migrations.CreateModel(
            name='lineMachineConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=255)),
                ('plant', models.CharField(max_length=255)),
                ('shopfloor', models.CharField(max_length=255)),
                ('product_id', models.CharField(max_length=255)),
                ('product_target', models.CharField(max_length=255)),
                ('assembly_line', models.CharField(max_length=255)),
                ('machine_id', models.CharField(max_length=255)),
                ('total_order', models.IntegerField(blank=True, null=True)),
                ('required_time', models.CharField(blank=True, max_length=255, null=True)),
                ('break_time', models.CharField(blank=True, default='03:00:00', max_length=255, null=True)),
                ('assigned_start_production', models.CharField(blank=True, max_length=255, null=True)),
                ('assigned_end_production', models.CharField(blank=True, max_length=255, null=True)),
                ('manager', models.CharField(max_length=255)),
                ('stage_name', models.CharField(blank=True, max_length=255, null=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_machine_config', to='production.productionplanning')),
            ],
            options={
                'db_table': 'line_machine_config',
            },
        ),
    ]
