# Generated by Django 4.2.6 on 2025-05-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flitrix',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lot_no', models.CharField(blank=True, max_length=255, null=True)),
                ('product_code', models.CharField(blank=True, max_length=255, null=True)),
                ('serial_no', models.CharField(blank=True, max_length=255, null=True)),
                ('actual', models.CharField(blank=True, max_length=255, null=True)),
                ('cycle_time', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'flitrix',
            },
        ),
    ]
