# Generated by Django 4.2.6 on 2025-05-17 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_flitrix'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flitrix',
            new_name='Filtrix',
        ),
    ]
