# Generated by Django 4.2.6 on 2025-05-17 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_rename_flitrix_filtrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtrix',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
