# Generated by Django 4.2.6 on 2025-05-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_filtrix_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filtrix2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shift', models.CharField(blank=True, max_length=255, null=True)),
                ('on_time', models.CharField(blank=True, max_length=255, null=True)),
                ('idle_time', models.CharField(blank=True, max_length=255, null=True)),
                ('planned', models.CharField(blank=True, max_length=255, null=True)),
                ('actual', models.CharField(blank=True, max_length=255, null=True)),
                ('performance', models.PositiveIntegerField(blank=True, null=True)),
                ('gap', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'flitrix2',
            },
        ),
    ]
