# Generated by Django 4.2.6 on 2025-05-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_filtrix2'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtrix2',
            name='day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filtrix2',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
