# Generated by Django 4.2.6 on 2025-05-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_filtrix2_day_filtrix2_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtrix2',
            name='actual',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filtrix2',
            name='planned',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
