# Generated by Django 4.2.6 on 2025-05-24 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_alter_filtrix2_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filtrix',
            old_name='lot_no',
            new_name='jobwork',
        ),
        migrations.RenameField(
            model_name='filtrix',
            old_name='serial_no',
            new_name='sku_code',
        ),
    ]
