# Generated by Django 4.2.6 on 2025-05-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_rename_lot_no_filtrix_jobwork_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtrix',
            name='line_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
