# Generated by Django 4.2.6 on 2025-05-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_filtrix_line_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtrix2',
            name='line_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
